/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CursorRelations = "model" | "model_version";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DstkMetadataCursors {
  cursor_id: Generated<string>;
  cursor_relation: CursorRelations;
  cursor_token: string;
  expiration: Generated<Timestamp>;
  id: Generated<number>;
}

export interface DstkMetadataPatchStatus {
  applied: Generated<boolean>;
  duration: number | null;
  patch: string;
}

export interface DstkUserAccounts {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: Generated<string>;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  id: Generated<number>;
  id_token: string | null;
  password: string | null;
  provider_id: Generated<string>;
  refresh_token: string | null;
  scope: string | null;
  user_id: string;
}

export interface DstkUserApiKeys {
  api_key_id: Generated<string>;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  enabled: boolean | null;
  expires_at: Timestamp | null;
  id: Generated<number>;
  key: string;
  last_refill_at: Timestamp | null;
  last_request: Timestamp | null;
  metadata: string | null;
  name: string | null;
  permissions: string | null;
  prefix: string | null;
  rate_limit_enabled: boolean | null;
  rate_limit_max: number | null;
  rate_limit_time_window: number | null;
  refill_amount: number | null;
  refill_interval: number | null;
  remaining: number | null;
  request_count: number | null;
  start: string | null;
  user_id: string;
}

export interface DstkUserInvitation {
  email: string;
  expires_at: Generated<Timestamp>;
  id: Generated<number>;
  invitation_id: Generated<string>;
  inviter_id: string;
  organization_id: string;
  role: string | null;
  status: string;
  teamid: string | null;
}

export interface DstkUserLog {
  actor_id: string;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  details: string;
  id: Generated<Int8>;
  log_id: Generated<string>;
  new_value: string;
  old_value: string;
  remote_addr: string;
  user_action: string;
  user_id: string;
}

export interface DstkUserMembers {
  date_created: Generated<Timestamp>;
  id: Generated<number>;
  member_id: Generated<string>;
  organization_id: string;
  role: string;
  teamid: string | null;
  user_id: string;
}

export interface DstkUserOrganizations {
  date_created: Generated<Timestamp>;
  id: Generated<number>;
  logo: string | null;
  metadata: string | null;
  name: string;
  organization_id: Generated<string>;
  slug: string;
}

export interface DstkUserProjects {
  created_by_id: string | null;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  is_archived: Generated<boolean>;
  modified_by_id: string | null;
  name: string;
  project_id: Generated<string>;
  team_id: string;
}

export interface DstkUserSessions {
  active_organization_id: string | null;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<number>;
  impersonated_by: string | null;
  ip_address: string | null;
  session_id: Generated<string>;
  token: string;
  user_agent: string | null;
  user_id: string;
}

export interface DstkUserTeams {
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  team_id: Generated<string>;
}

export interface DstkUserTwoFactor {
  backup_codes: string;
  id: Generated<number>;
  secret: string;
  two_factor_id: Generated<string>;
  user_id: string;
}

export interface DstkUserUser {
  ban_expires: number | null;
  ban_reason: string | null;
  banned: boolean | null;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  image: string | null;
  is_admin: Generated<boolean>;
  is_approved: Generated<boolean>;
  is_disabled: Generated<boolean>;
  is_email_verified: Generated<boolean>;
  is_mfa_enrolled: Generated<boolean>;
  password: string;
  real_name: string;
  role: string | null;
  user_id: Generated<string>;
  user_name: string;
}

export interface DstkUserVerifications {
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<number>;
  identifier: string;
  value: string;
  verification_id: Generated<string>;
}

export interface RegistryModels {
  created_by_id: string | null;
  current_model_version_id: string | null;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  is_archived: Generated<boolean>;
  metadata: Json | null;
  model_id: Generated<string>;
  model_name: string;
  modified_by_id: string | null;
  project_id: string;
  storage_provider_id: string;
}

export interface RegistryModelVersions {
  created_by_id: string | null;
  date_created: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  is_archived: Generated<boolean>;
  is_finalized: Generated<boolean>;
  metadata: Json | null;
  model_id: string;
  model_version_id: Generated<string>;
  numeric_version: number;
  s3_prefix: string | null;
}

export interface RegistryStorageProviders {
  access_key_id: string;
  bucket: string;
  created_by_id: string | null;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  endpoint_url: string;
  id: Generated<number>;
  is_archived: Generated<boolean>;
  modified_by_id: string | null;
  owner_id: string | null;
  provider_id: Generated<string>;
  region: string;
  secret_access_key: string;
  team_id: string;
}

export interface DB {
  "dstk_metadata.cursors": DstkMetadataCursors;
  "dstk_metadata.patch_status": DstkMetadataPatchStatus;
  "dstk_user.accounts": DstkUserAccounts;
  "dstk_user.api_keys": DstkUserApiKeys;
  "dstk_user.invitation": DstkUserInvitation;
  "dstk_user.log": DstkUserLog;
  "dstk_user.members": DstkUserMembers;
  "dstk_user.organizations": DstkUserOrganizations;
  "dstk_user.projects": DstkUserProjects;
  "dstk_user.sessions": DstkUserSessions;
  "dstk_user.teams": DstkUserTeams;
  "dstk_user.two_factor": DstkUserTwoFactor;
  "dstk_user.user": DstkUserUser;
  "dstk_user.verifications": DstkUserVerifications;
  "registry.model_versions": RegistryModelVersions;
  "registry.models": RegistryModels;
  "registry.storage_providers": RegistryStorageProviders;
}
