---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dstk-minio
    app.kubernetes.io/name: dstk-minio
  name: dstk-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dstk-minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dstk-minio
        app.kubernetes.io/name: dstk-minio
    spec:
      initContainers:
      - name: install
        image: alpine:latest
        command:
        - mkdir
        - -p
        - /data/dstk-registry
      containers:
      - args:
          - server
          - /data
          - --console-address
          - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        image: minio/minio:latest
        name: dstk-minio
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dstk-minio
  name: dstk-minio
spec:
  ports:
    - name: "9001"
      port: 9001
  selector:
    io.kompose.service: dstk-minio
