# apiVersion: v1
# kind: Secret
# metadata:
#   name: storage-provider-key
#   labels:
#     io.kompose.service: dstk-apollo
#     app.kubernetes.io/name: dstk-apollo
# data:
#   enc-key: SW1JbkRhbmdlcgo=

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dstk-apollo
    app.kubernetes.io/name: dstk-apollo
  name: dstk-apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dstk-apollo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dstk-apollo
        app.kubernetes.io/name: dstk-apollo
    spec:
      containers:
        - name: dstk-apollo
          image: dstk-apollo
          # env:
          # - name: STORAGE_PROVIDER_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: storage-provider-key
          #       key: enc-key

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dstk-apollo
  name: dstk-apollo
spec:
  ports:
    - name: "4000"
      port: 4000
  selector:
    io.kompose.service: dstk-apollo
