apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: dstk
manifests:
  rawYaml:
  - minio/minio.k8s.yml
  - postgres/postgres.k8s.yml
build:
  artifacts:
  - image: dstk-postgres
    context: postgres
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl: {}
  statusCheckDeadlineSeconds: 600
profiles:
- name: dstk-dev
  portForward:
    - resourceType: service
      resourceName: postgres
      port: 5432
      localPort: 5432
    - resourceType: service
      resourceName: minio
      port: 9001
      localPort: 9001