---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres
    app.kubernetes.io/name: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: postgres
        app.kubernetes.io/name: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: dstk
        image: postgres:15.3
        name: postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
  selector:
    io.kompose.service: postgres
