apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    io.kompose.service: dstk-postgres
    app.kubernetes.io/name: dstk-postgres
data:
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dstk-postgres
    app.kubernetes.io/name: dstk-postgres
  name: dstk-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dstk-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dstk-postgres
        app.kubernetes.io/name: dstk-postgres
    spec:
      containers:
        - name: postgres
          image: dstk-postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dstk-postgres
  name: dstk-postgres
spec:
  ports:
    - name: "5432"
      port: 5432
  selector:
    io.kompose.service: dstk-postgres
