apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dstk-web
    app.kubernetes.io/name: dstk-web
  name: dstk-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dstk-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dstk-web
        app.kubernetes.io/name: dstk-web
    spec:
      containers:
        - name: dstk-web
          image: dstk-web

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dstk-web
  name: dstk-web
spec:
  ports:
    - name: "5173"
      port: 5173
  selector:
    io.kompose.service: dstk-web
